#+TITLE: Laboratory Methods for Quantitative Acylcarnitines in Biological Matrices
#+AUTHOR: Matthew Henderson, PhD, FCACB
#+DATE: \today

* Introduction
- carnitine (\beta{}-hydroxy-\gamma{}-N-trimethylaminobutyric acid) is
  an endogenous quaternary ammonium compound synthesized from lysine
  and methionine.
- L-Carnitine has been described as a "conditionally essential"
  nutrient for humans.
- populations with an exogenous carnitine requirement include:
  - infants (premature and full-term),
  - patients on long-term parenteral nutrition,
  - perhaps children.
- exogenous carnitine is required to maintain "normal" (in the
  epidemiologic sense) plasma or serum carnitine concentrations in
  humans of all ages.
- primary function is to shuttle long chain fatty acids to the
  mitochondrial matrix, for \beta{}-oxidation.
- acylcarnitines are markers for FAODs and OAs

\vspace{2em}

#+BEGIN_EXPORT LaTeX
\chemname{\chemfig[][scale=.5]{H3C-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-OH)-CH_2-C([1]=O)([7]-O^{-})}}{\tiny Carnitine}
\hspace{3em}
\chemname{\chemfig[][scale=.5]{H3C-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-O-C([0]=O)-{\color{red}R})-CH_2-C([1]=O)([7]-O^{-})}}{\tiny Acylcarnitine}
%\chemname{\chemfig[][scale=.5]{H3C-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-O-C([0]=O)-{\color{red}R})-CH_2-C([2]=O)-O-CH_2-CH_2-CH_2-CH_3}}{\tiny Acylcarnitine, butyl ester}
#+END_EXPORT

* Diagnostic FIA-MS/MS
- see [[AAAC]]
* TODO Free and Total Carnitine
- Method?
** Fractional Tubular Re-absorption of Carnitine

#+BEGIN_EXPORT LaTeX
\begin{equation*}
FTR_{carnitine}\% = \left( 1 -  \frac{carnitine_{urine} \cdot creatinine_{plasma}}{carnitine_{plasma} \cdot creatinine_{urine}}\right) \cdot 100
\end{equation*}
#+END_EXPORT

- normally >98%, \Downarrow in CUD

** Free/Total Carnitine

\[
\frac{Free_{carnitine}}{Total_{carnitine}} = \frac{C_0}{\sum_{0}^{18} C_n}
\]

- \Downarrow in CUD, < 5-10% of normal 
